# - Dockerfile configurations
FROM python:3.10.1-alpine3.15
LABEL DESCRIPTION="order-api" 
COPY requirements.txt /
RUN pip3 install -r requirements.txt
WORKDIR /usr/src/app
COPY . .
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "82", "--reload"]

# docker image build -t order-api:latest .

# docker container run --rm -it -v ${pwd}:/usr/src/app --env-file .env -p 81:81 --name order-api order-api:latest
